In [18]:
x=[10,20,30,50,48,45,1,2,3]
print(x)

[10, 20, 30, 50, 48, 45, 1, 2, 3]

In [31]:
x.append(23)
print("x value after append:", x)

x.extend([56,25])
print("x value after extend:", x)

x.insert(55,85)
print("x value after insert:", x)

x.remove(56)
print("x value after remove:", x)

x.pop(3)
print("x value after pop:", x)


x.sort()
print("After sorting x number:", x)

x.reverse()
print("After reverse x number:", x)

x.clear()
print("After clear x number:", x)

x value after append: [85, 85, 85, 85, 85, 85, 85, 56, 56, 56, 56, 56, 30, 25, 25, 25, 25, 25, 25, 25, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 10, 3, 2, 23]
x value after extend: [85, 85, 85, 85, 85, 85, 85, 56, 56, 56, 56, 56, 30, 25, 25, 25, 25, 25, 25, 25, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 10, 3, 2, 23, 56, 25]
x value after insert: [85, 85, 85, 85, 85, 85, 85, 56, 56, 56, 56, 56, 30, 25, 25, 25, 25, 25, 25, 25, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 10, 3, 2, 23, 56, 25, 85]
x value after remove: [85, 85, 85, 85, 85, 85, 85, 56, 56, 56, 56, 30, 25, 25, 25, 25, 25, 25, 25, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 10, 3, 2, 23, 56, 25, 85]
x value after pop: [85, 85, 85, 85, 85, 85, 56, 56, 56, 56, 30, 25, 25, 25, 25, 25, 25, 25, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 10, 3, 2, 23, 56, 25, 85]
After sorting x number: [2, 3, 10, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 30, 56, 56, 56, 56, 56, 85, 85, 85, 85, 85, 85, 85]
After reverse x number: [85, 85, 85, 85, 85, 85, 85, 56, 56, 56, 56, 56, 30, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 10, 3, 2]
After clear x number: []

In [35]:
Student = ("Anand", "Bharath", "varsha")

# Attempt to change second name
Student[1] = "cherry"

# Tupples are unmutable since there cant be changed, inorder to maintain an accuracy in the data

TypeError: 'tuple' object does not support item assignment

In [36]:
my_set = {1, 2, 3, 4, 4, 5, 5}
print("Set:", my_set)

Set: {1, 2, 3, 4, 5}

In [37]:
# duplicate values are removed in the set it print only unique values

In [47]:
emp={"name":"varsha","age":"32","city":"hyd"}
emp["age"]=31
emp['email']="vkolariya@gmail.com"
emp

{'name': 'varsha', 'age': 31, 'city': 'hyd', 'email': 'vkolariya@gmail.com'}

In [50]:
age=int(input("please enter the age:"))
if(age>=18):
    print("person is eligible for vote")
else:
    print("person is not eligible for vote")

please enter the age: 56

person is eligible for vote

In [61]:
marks=12
if(marks>=90):
    print("Grade A")
else:
    if(marks>=75 and marks<=89):
        print("Grade B")
    else:
        if (marks>=50 and marks<=74):
            print("Grade C")
        else:
            print("Fail")

Fail

In [77]:
number=12
if (number>0):
    print("Positive number")
    if (number%2==0):
        print("Even number")
    else:
        print("odd number")
elif number==0:
    print("zero")
else:
    print("negative")

Positive number
Even number

In [84]:
import numpy as np
scalar=np.array(5)
print(scalar)
array_1d=np.array([15,20,30])
array_2d=np.array([[10,20,30],[40,50,56]])
print(array_1d,array_2d)

5
[15 20 30] [[10 20 30]
 [40 50 56]]

In [85]:
random_array = np.random.randint(0, 101, size=(4, 4))
print("4x4 Random Array:\n", random_array)

4x4 Random Array:
 [[75 75 70  7]
 [25 38 66  0]
 [63 78 53 21]
 [91 47 16 87]]

In [90]:
import pandas as pd
data=np.array([[10,20,30],[2,3,4],[5,6,9]])
df=pd.DataFrame(data,columns=['A','B','C'])
df

    A   B   C
0  10  20  30
1   2   3   4
2   5   6   9

In [123]:
df={'Name':["Rohi","Mahi","Mahi","dolly","alliy","vahu","vansh","ansh","aruhi","arushi"],'Age':[30,50,50,88,45,56,98,45,52,44],
    'city':['hyd','hyd','hyd','hyd','pune','pune','pune','pune','delhi','delhi'],
    'Salary':[60000,70000,70000,50000,400000,np.nan,80000,50000,400000,60000]}
df1=pd.DataFrame(df)

In [124]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   city    10 non-null     object
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [125]:
df1.describe()

             Age         Salary
count  10.000000       9.000000
mean   55.800000  137777.777778
std    20.916766  148977.999867
min    30.000000   50000.000000
25%    45.000000   60000.000000
50%    50.000000   70000.000000
75%    55.000000   80000.000000
max    98.000000  400000.000000

In [126]:
df2=df1[['Name','city']]

In [127]:
df3=df2.drop('city',axis=1)

In [128]:
df_salary_mean=df1["Salary"].mean
df1["Salary"].isnull

<bound method Series.isnull of 0     60000.0
1     70000.0
2     70000.0
3     50000.0
4    400000.0
5         NaN
6     80000.0
7     50000.0
8    400000.0
9     60000.0
Name: Salary, dtype: float64>

In [129]:
df1["Salary"].fillna(df_salary_mean)

0                                              60000.0
1                                              70000.0
2                                              70000.0
3                                              50000.0
4                                             400000.0
5    <bound method Series.mean of 0     60000.0\n1 ...
6                                              80000.0
7                                              50000.0
8                                             400000.0
9                                              60000.0
Name: Salary, dtype: object

In [130]:
df1["Salary"]=df1["Salary"].fillna(df_salary_mean)

In [131]:
df1["Salary"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: Salary
Non-Null Count  Dtype
--------------  -----
10 non-null     object
dtypes: object(1)
memory usage: 212.0+ bytes

In [132]:
df1.drop_duplicates()

     Name  Age   city                                             Salary
0    Rohi   30    hyd                                            60000.0
1    Mahi   50    hyd                                            70000.0
3   dolly   88    hyd                                            50000.0
4   alliy   45   pune                                           400000.0
5    vahu   56   pune  <bound method Series.mean of 0     60000.0\n1 ...
6   vansh   98   pune                                            80000.0
7    ansh   45   pune                                            50000.0
8   aruhi   52  delhi                                           400000.0
9  arushi   44  delhi                                            60000.0